### PR TITLE
Prevent batch executions from being suspended due to callback failures

### PR DESCRIPTION
**Pull request by bugflux**
This change prevents an issue where, if a call to `onFlushFailure` throws an exception, subsequent executions of the timer task will be suspended.

Additionally, it adds additional protection to the run method, to prevent regressions in changes to the `flush` method.

### CODE REVIEW

**Comment by rfer** [comment]
@bugflux I'm having hard time justifying these changes. This is a problem upstream, not here.

It makes sense to propagate these exceptions. Having it like this is very specific to your use-case. What if the upstream logic is expecting some exception to be thrown in case of failure?

In truth, if the run() method can throw an exception, it should probably not even be runnable at all. 
I agree with the logging, as it allow us to have more fine grain insight of what went wrong, given the lack of a better alternative as there are no specific exceptions nor error codes. But the exceptions should be propagated, and have your upstream code wrap the call to run().

**Comment by bugflux** [comment]
Hi Ricardo,

I’m ok with adjusting however you like.

However, I think the side effect of the batch being suspended as a result
of a failed call to onFlushFailure either needs to be prevented or clearly
supported/documented.

**Comment by bugflux** [comment]
As for the wrap to “run”, I tend to agree.

I considered making the timer task a lambda that calls run while catching exceptions.

**Comment by rfer** [comment]
@bugflux I misinterpreted this. I forgot about the Scheduled Executor on the AbstractBatch itself.

What I said still stands. And in light of that, we should handle this on the submit to AbstractBatch's Scheduled Executor.

**Comment by bugflux** [comment]
I am torn, let me explain what my thought process was and I can adjust the pull request if you want me to:

I agree with (1) not suppressing the exception in the onFlushFailure call.
I also agree with (2) handling this at the submission to the scheduled execution

However, I think that the `run()` method, despite being public, doesn't seem part of the "API" of AbstractBatch, as its logging clearly states that it's running in the scope of a scheduled trigger.

So should we (3.1) make the AbstractBatch no longer a Runnable, or (3.2) embrace the `run()` method as THE place where the logic for the scheduled execution takes place?

**Pull request merged**
